# Generated by Django 5.2.3 on 2025-07-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
